# website settings
website:
  title: "SoFaCycling"
  description: "Our cycling adventures"
  image: img/SoFaCycling.jpg
  
  favicon: img/bicycle.svg
  
  # navigation bar at the top of the website
  navbar:
    pinned: false
    
    # sub-pages
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "About"
        href: about/index.qmd
    
    # social media handles
    right:
      - icon: strava
        href: https://www.strava.com/athletes/18210938
      - icon: strava
        href: https://www.strava.com/athletes/35725334
      - icon: github
        href: https://github.com/SoFaCycling
      - icon: envelope
        aria-label: email
        href: "mailto:sofacycling@gmail.com"  
  
  

# ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 SoFaCycling CC BY-NC 4.0</span>
    right: |
      <div class="faux-block">
        <span>Built with {{< bi heart>}}, <a href="https://quarto.org/"> Quarto<sup>&#174;</sup></a></span>
        <span>, and <a href="https://getbootstrap.com/">{{< bi bootstrap>}}</a></span>
        <span>|&nbsp; Source code on <a href="https://github.com/SoFaCycling">{{< bi github>}}</a></span>
      </div>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

resources:
  - blog/posts/**/track.json

exclude:
  - scripts/

execute:
  freeze: false

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    
    toc: false
    code-link: true
    anchor-sections: true
    reference-location: margin
    footnotes-hover: true